# Prometheus configuration for microservice planner
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  # Node exporter (if added in the future)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis exporter (if added in the future)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL exporter (if added in the future)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Application metrics (when backend is added)
  - job_name: 'microplan-api'
    static_configs:
      - targets: ['microplan:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

# Alerting configuration (for future use)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093